default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "evin") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: localhost

development:
  <<: *default
  database: evin_development

test:
  <<: *default
  database: evin_test

production:
  <<: *default
  database: evin_production
